### ISSUE TITLE
Request to add title-case support.

### ISSUE THREAD

**Issue by maximus136** [maximus136/change-string-case#2]
With title-case support enabled, switching from any case to title-case would result in a phrase along the lines of `This Is A Title` - with proper spacing, and each word starting with an uppercase letter.

**Comment by jcardoz** [comment]
gonna try this out

**Comment by jcardoz** [comment]
@maximus136 Can you update the read-me to debug the extension. VSCode extension documentation is really useless

**Comment by jcardoz** [comment]
Added Title case support
https://github.com/maximus136/change-string-case/pull/5

**Comment by maximus136** [comment]
> Added Title case support
> #5

Closing
